[2020-12-10 14:35:19,491] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_PG.create_table 2020-12-10T09:00:00+00:00 [queued]>
[2020-12-10 14:35:19,597] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_PG.create_table 2020-12-10T09:00:00+00:00 [queued]>
[2020-12-10 14:35:19,599] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-10 14:35:19,600] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-10 14:35:19,601] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-10 14:35:19,663] {taskinstance.py:901} INFO - Executing <Task(PostgresOperator): create_table> on 2020-12-10T09:00:00+00:00
[2020-12-10 14:35:19,684] {standard_task_runner.py:54} INFO - Started process 77399 to run task
[2020-12-10 14:35:19,972] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Write_data_to_PG', 'create_table', '2020-12-10T09:00:00+00:00', '--job_id', '652', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/FileSensorDemo.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmphm3txvyh']
[2020-12-10 14:35:19,982] {standard_task_runner.py:78} INFO - Job 652: Subtask create_table
[2020-12-10 14:43:02,392] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Write_data_to_PG.create_table 2020-12-10T09:00:00+00:00 [running]> Sundars-MacBook-Pro.local
[2020-12-10 14:43:04,590] {local_task_job.py:113} ERROR - Heartbeat time limited exceeded!
[2020-12-10 14:43:04,597] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 77399
[2020-12-10 14:43:04,602] {helpers.py:291} INFO - Process psutil.Process(pid=77399, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='14:35:19') (77399) terminated with exit code Negsignal.SIGTERM
