[2020-11-25 04:11:29,555] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: First_DAG_for_test.read_csv 2020-11-24T19:00:00+00:00 [queued]>
[2020-11-25 04:11:29,566] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: First_DAG_for_test.read_csv 2020-11-24T19:00:00+00:00 [queued]>
[2020-11-25 04:11:29,566] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-11-25 04:11:29,566] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-11-25 04:11:29,566] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-11-25 04:11:29,573] {taskinstance.py:901} INFO - Executing <Task(BashOperator): read_csv> on 2020-11-24T19:00:00+00:00
[2020-11-25 04:11:29,575] {standard_task_runner.py:54} INFO - Started process 70723 to run task
[2020-11-25 04:11:29,590] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'First_DAG_for_test', 'read_csv', '2020-11-24T19:00:00+00:00', '--job_id', '210', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/sampleDag.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpz6iemehy']
[2020-11-25 04:11:29,591] {standard_task_runner.py:78} INFO - Job 210: Subtask read_csv
[2020-11-25 04:11:29,617] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: First_DAG_for_test.read_csv 2020-11-24T19:00:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-11-25 04:11:29,632] {bash_operator.py:113} INFO - Tmp dir root location: 
 /var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T
[2020-11-25 04:11:29,634] {bash_operator.py:136} INFO - Temporary script location: /var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/airflowtmpc__byyhy/read_csves0qys_0
[2020-11-25 04:11:29,634] {bash_operator.py:146} INFO - Running command: python3 /Users/sundarb/Documents/DEWorkspace/postgresSample.conf
[2020-11-25 04:11:29,639] {bash_operator.py:153} INFO - Output:
[2020-11-25 04:11:29,667] {bash_operator.py:157} INFO -   File "/Users/sundarb/Documents/DEWorkspace/postgresSample.conf", line 1
[2020-11-25 04:11:29,668] {bash_operator.py:157} INFO -     input{
[2020-11-25 04:11:29,668] {bash_operator.py:157} INFO -          ^
[2020-11-25 04:11:29,668] {bash_operator.py:157} INFO - SyntaxError: invalid syntax
[2020-11-25 04:11:29,670] {bash_operator.py:161} INFO - Command exited with return code 1
[2020-11-25 04:11:29,675] {taskinstance.py:1150} ERROR - Bash command failed
Traceback (most recent call last):
  File "/Users/sundarb/Documents/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/sundarb/Documents/anaconda3/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 165, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-11-25 04:11:29,681] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=First_DAG_for_test, task_id=read_csv, execution_date=20201124T190000, start_date=20201124T224129, end_date=20201124T224129
[2020-11-25 04:11:34,548] {local_task_job.py:102} INFO - Task exited with return code 1
